




CREATE TABLE Склад (
 primaryKey UUID NOT NULL,
 КодСклада INT NULL,
 ИмяСклада VARCHAR(255) NULL,
 ТЧАктаПриемки UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ТН (
 primaryKey UUID NOT NULL,
 НомерТН INT NULL,
 Поставщик VARCHAR(255) NULL,
 НомерТС VARCHAR(255) NULL,
 Материал VARCHAR(255) NULL,
 Колво INT NULL,
 АктПриемки UUID NOT NULL,
 ТЧАктаПриемки UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE Сотрудники (
 primaryKey UUID NOT NULL,
 ФИО VARCHAR(255) NULL,
 Должность VARCHAR(255) NULL,
 Табель VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE АктПриемки (
 primaryKey UUID NOT NULL,
 НомерАкта INT NULL,
 ДатаПриемки VARCHAR(255) NULL,
 Сотрудники UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ТЧАктаПриемки (
 primaryKey UUID NOT NULL,
 НомерПозиции INT NULL,
 АктПриемки UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMNETLOCKDATA (
 LockKey VARCHAR(300) NOT NULL,
 UserName VARCHAR(300) NOT NULL,
 LockDate TIMESTAMP(3) NULL,
 PRIMARY KEY (LockKey));


CREATE TABLE STORMSETTINGS (
 primaryKey UUID NOT NULL,
 Module VARCHAR(1000) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 "User" VARCHAR(255) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMAdvLimit (
 primaryKey UUID NOT NULL,
 "User" VARCHAR(255) NULL,
 Published BOOLEAN NULL,
 Module VARCHAR(255) NULL,
 Name VARCHAR(255) NULL,
 Value TEXT NULL,
 HotKeyData INT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERSETTING (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMWEBSEARCH (
 primaryKey UUID NOT NULL,
 Name VARCHAR(255) NOT NULL,
 "Order" INT NOT NULL,
 PresentView VARCHAR(255) NOT NULL,
 DetailedView VARCHAR(255) NOT NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERDETAIL (
 primaryKey UUID NOT NULL,
 Caption VARCHAR(255) NOT NULL,
 DataObjectView VARCHAR(255) NOT NULL,
 ConnectMasterProp VARCHAR(255) NOT NULL,
 OwnerConnectProp VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE STORMFILTERLOOKUP (
 primaryKey UUID NOT NULL,
 DataObjectType VARCHAR(255) NOT NULL,
 Container VARCHAR(255) NULL,
 ContainerTag VARCHAR(255) NULL,
 FieldsToView VARCHAR(255) NULL,
 FilterSetting_m0 UUID NOT NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE UserSetting (
 primaryKey UUID NOT NULL,
 AppName VARCHAR(256) NULL,
 UserName VARCHAR(512) NULL,
 UserGuid UUID NULL,
 ModuleName VARCHAR(1024) NULL,
 ModuleGuid UUID NULL,
 SettName VARCHAR(256) NULL,
 SettGuid UUID NULL,
 SettLastAccessTime TIMESTAMP(3) NULL,
 StrVal VARCHAR(256) NULL,
 TxtVal TEXT NULL,
 IntVal INT NULL,
 BoolVal BOOLEAN NULL,
 GuidVal UUID NULL,
 DecimalVal DECIMAL(20,10) NULL,
 DateTimeVal TIMESTAMP(3) NULL,
 PRIMARY KEY (primaryKey));


CREATE TABLE ApplicationLog (
 primaryKey UUID NOT NULL,
 Category VARCHAR(64) NULL,
 EventId INT NULL,
 Priority INT NULL,
 Severity VARCHAR(32) NULL,
 Title VARCHAR(256) NULL,
 Timestamp TIMESTAMP(3) NULL,
 MachineName VARCHAR(32) NULL,
 AppDomainName VARCHAR(512) NULL,
 ProcessId VARCHAR(256) NULL,
 ProcessName VARCHAR(512) NULL,
 ThreadName VARCHAR(512) NULL,
 Win32ThreadId VARCHAR(128) NULL,
 Message VARCHAR(2500) NULL,
 FormattedMessage TEXT NULL,
 PRIMARY KEY (primaryKey));



 ALTER TABLE Склад ADD CONSTRAINT FK23e62b8c966c2d22b284311ed67485fc8c02d211 FOREIGN KEY (ТЧАктаПриемки) REFERENCES ТЧАктаПриемки; 
CREATE INDEX Index23e62b8c966c2d22b284311ed67485fc8c02d211 on Склад (ТЧАктаПриемки); 

 ALTER TABLE ТН ADD CONSTRAINT FKa24ca6ca32f3f5da74d246943e1bb1c5a8ec0171 FOREIGN KEY (АктПриемки) REFERENCES АктПриемки; 
CREATE INDEX Indexa24ca6ca32f3f5da74d246943e1bb1c5a8ec0171 on ТН (АктПриемки); 

 ALTER TABLE ТН ADD CONSTRAINT FK2dc682f31ba2c2ba569266a10cbf066a3243ac11 FOREIGN KEY (ТЧАктаПриемки) REFERENCES ТЧАктаПриемки; 
CREATE INDEX Index2dc682f31ba2c2ba569266a10cbf066a3243ac11 on ТН (ТЧАктаПриемки); 

 ALTER TABLE АктПриемки ADD CONSTRAINT FK96a348ff0dd82a8e693a83f05e7d7bb16df138da FOREIGN KEY (Сотрудники) REFERENCES Сотрудники; 
CREATE INDEX Index96a348ff0dd82a8e693a83f05e7d7bb16df138da on АктПриемки (Сотрудники); 

 ALTER TABLE ТЧАктаПриемки ADD CONSTRAINT FK9e1aacb51157e4a61e68f65c8e44c13dcb11991b FOREIGN KEY (АктПриемки) REFERENCES АктПриемки; 
CREATE INDEX Index9e1aacb51157e4a61e68f65c8e44c13dcb11991b on ТЧАктаПриемки (АктПриемки); 

 ALTER TABLE STORMWEBSEARCH ADD CONSTRAINT FKc4378e39870eb056aec84088683297a01d2a6200 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERDETAIL ADD CONSTRAINT FK921d16269835017e2a0d0e29ad6fb175454a70d0 FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

 ALTER TABLE STORMFILTERLOOKUP ADD CONSTRAINT FKce38ef0db3f01a53acaa49fed8853fb941ad47ba FOREIGN KEY (FilterSetting_m0) REFERENCES STORMFILTERSETTING; 

